### ISSUE TITLE
Crash 'out of memory'

### ISSUE THREAD

**Issue by za267** [thomasrudin-mt/mapserver#11]
Hi there,

I'm running release version 1.0.0 mapserver-linux-x86_64 and it crashes with "fatal error: runtime: out of memory"

- It used up to around 1Gbs and there were still over 4Gbs free.

- My server uses a postgresql backend.

Just to add a bit of information: The map generation appeared to be going very well and I could tell that it was more than halfway done from the site that it was generating.

**Comment by thomasrudin** [comment]
Hmm, yeah, that happened to me once on a large map:
Can you try to reduce the cache values in the `mapserver.json` file:
```json
{
	"mapblockaccessor": {
		"expiretime": "500ms",
		"purgetime": "1000ms"
	}
}
```
Those are the main memory-hogs, i suggest you turn them down by a factor of 10 (expiretime=50ms, purgetime=100ms)

I may have to find a better caching solution thats memory-based, not time-based though..

**Comment by za267** [comment]
@thomasrudin I'll give that a try and let you know.

**Comment by za267** [comment]
I tried reducing it to 50ms and 100ms respectively but the result was the same (out of memory crash).  Then I tried to reduce it again to 5ms and 10ms.  Same result.  Do I need to reset anything or just restart the mapserver process?

**Comment by za267** [comment]
Modifying the renderingfetchlimit was working for a short bit and then it segfaulted: 

```
INFO[0000] Starting mapserver                            version=1.0.0
INFO[0000] Loading default colors                        filename=/colors.txt prefix=colormapping size=704248 useLocal=false
INFO[0000] Loaded default colors                         count=16108
INFO[0000] Loading colors from filesystem                filename=colors.txt
INFO[0000] Loaded custom colors                          count=15437
INFO[0000] Migrating database                            filename=mapserver.sqlite prefix=mapobjectdb.sqlite
INFO[0000] Migration completed                           elapsed="610.9µs" prefix=mapobjectdb.sqlite
INFO[0000] Starting http server                          port=8080 webdev=false
INFO[0000] Starting incremental rendering job            LastMtime=1551043605
INFO[0018] incremental rendering                         elapsed=18.796479483s lastMtime=1551060666692 mapblocks=770 secondsDiff=-1549509543 tiles=153
INFO[0045] incremental rendering                         elapsed=26.67580055s lastMtime=1551093717711 mapblocks=791 secondsDiff=-1549542594 tiles=213
INFO[0056] incremental rendering                         elapsed=11.383072888s lastMtime=1551094030177 mapblocks=963 secondsDiff=-1549542906 tiles=85
INFO[0071] incremental rendering                         elapsed=14.300499343s lastMtime=1551094364160 mapblocks=613 secondsDiff=-1549543240 tiles=100
INFO[0090] incremental rendering                         elapsed=18.893434485s lastMtime=1551106626482 mapblocks=805 secondsDiff=-1549555502 tiles=149
INFO[0111] incremental rendering                         elapsed=21.405812278s lastMtime=1551110046249 mapblocks=652 secondsDiff=-1549558922 tiles=165
INFO[0122] incremental rendering                         elapsed=11.165045895s lastMtime=1551110169680 mapblocks=983 secondsDiff=-1549559045 tiles=133
INFO[0132] incremental rendering                         elapsed=9.649146821s lastMtime=1551110319052 mapblocks=879 secondsDiff=-1549559195 tiles=125
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x789175]

goroutine 35116 [running]:
mapserver/mapblockparser.(*Inventory).IsEmpty(0x0, 0xc00b148bd0)
	/app/mapblockparser/mapblock.go:50 +0x5
mapserver/mapobject.(*SmartShopBlock).onMapObject(0x12db3f8, 0xa, 0x1, 0x5, 0xc00a7e8400, 0xc00000d8a0, 0xba1c28, 0x11)
	/app/mapobject/smartshop.go:19 +0x173
mapserver/mapobject.(*Listener).OnEvent.func1(0xa, 0x1, 0x5)
	/app/mapobject/listener.go:66 +0x4f9
mapserver/mapblockparser.IterateMapblock(0xc00728a9b8)
	/app/mapblockparser/iterate.go:7 +0x41
mapserver/mapobject.(*Listener).OnEvent(0xc0006fe7e0, 0xba1c17, 0x11, 0xb051e0, 0xc00a7e8400)
	/app/mapobject/listener.go:53 +0x274
mapserver/eventbus.(*Eventbus).Emit(0xc0001bb7a0, 0xba1c17, 0x11, 0xb051e0, 0xc00a7e8400)
	/app/eventbus/eventbus.go:35 +0xcc
mapserver/mapblockaccessor.(*MapBlockAccessor).GetMapBlock(0xc0001bb7c0, 0xc0072a3580, 0x0, 0x0, 0x0)
	/app/mapblockaccessor/get.go:40 +0x253
mapserver/mapblockrenderer.(*MapBlockRenderer).Render(0xc0006fe620, 0xc0072a54e0, 0xc0072a5500, 0x0, 0x0, 0x0)
	/app/mapblockrenderer/renderer.go:113 +0xf23
mapserver/tilerenderer.(*TileRenderer).renderImage(0xc000700a80, 0xc0072a5420, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/app/tilerenderer/renderer.go:128 +0x4f3
mapserver/tilerenderer.(*TileRenderer).renderImage(0xc000700a80, 0xc0072a4640, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/app/tilerenderer/renderer.go:157 +0x93d
mapserver/tilerenderer.(*TileRenderer).Render(0xc000700a80, 0xc0072a4640, 0x1, 0x1, 0xc00728bf70, 0x0, 0x0)
	/app/tilerenderer/renderer.go:52 +0x42
mapserver/tilerendererjob.worker(0xc0001a6000, 0xc008bf54a0, 0xc00002e1c0)
	/app/tilerendererjob/worker.go:22 +0x3bb
created by mapserver/tilerendererjob.renderMapblocks
	/app/tilerendererjob/common.go:29 +0x13b
```

**Comment by za267** [comment]
So it seems to be working... I set the renderingfetchlimit back to 10,000 and its fine now... I've had to disable smartshop...

**Comment by thomasrudin** [comment]
Strange, the `renderingfetchlimit` setting is only for sqlite3 :confused: 
Can you tell me if everything worked without the smartshop-feature?

I'll try to migrate my main map (postgres) too in the next week, i guess there are still some bugs waiting :smile:

**Comment by za267** [comment]
Right, so I put the renderingfetchlimit values back to what they were at some point after removing the smartshop and indeed, everything was working.   So I'm not sure whether there was a relation between the initial running out of memory problem and the smartshops or not.  

If there is a way to 'reset' the map, I could give it another try if you like just for debugging purposes.  I'm thinking deleting the sqlite file it generated, and the tiles directory?

**Comment by za267** [comment]
By the way - this is really great!  Thank you very much for this mapper!

**Comment by thomasrudin** [comment]
Nice, that `Dockerfile` was still warm at the time you used it :smile:
Good to hear that everything worked so far, i'm closing this issue, if you have further problems feel free to open a new one..
