### ISSUE TITLE
Websocket crash

### ISSUE THREAD

**Issue by thomasrudin** [thomasrudin-mt/mapserver#18]
```
mapserver_1          | 2019/03/18 19:00:44 http: panic serving 172.30.0.9:39922: runtime error: invalid memory address or nil pointer dereference
mapserver_1          | goroutine 46736 [running]:
mapserver_1          | net/http.(*conn).serve.func1(0xc0117f30e0)
mapserver_1          | 	/usr/lib/go-1.12/src/net/http/server.go:1769 +0xc9
mapserver_1          | panic(0xb408e0, 0x1330f80)
mapserver_1          | 	/usr/lib/go-1.12/src/runtime/panic.go:522 +0x1b5
mapserver_1          | github.com/gorilla/websocket.(*Conn).WriteMessage(0x0, 0x1, 0xc0986384c0, 0x3e, 0x40, 0x0, 0xcef0e0)
mapserver_1          | 	/root/go/pkg/mod/github.com/gorilla/websocket@v1.4.0/conn.go:742 +0x37
mapserver_1          | mapserver/web.(*WS).ServeHTTP(0xc000226d40, 0xcfa820, 0xc04df649a0, 0xc04d982b00)
mapserver_1          | 	/server/web/ws.go:72 +0x1ba
mapserver_1          | net/http.(*ServeMux).ServeHTTP(0xc0001299c0, 0xcfa820, 0xc04df649a0, 0xc04d982b00)
mapserver_1          | 	/usr/lib/go-1.12/src/net/http/server.go:2375 +0x1d6
mapserver_1          | net/http.serverHandler.ServeHTTP(0xc0001421a0, 0xcfa820, 0xc04df649a0, 0xc04d982b00)
mapserver_1          | 	/usr/lib/go-1.12/src/net/http/server.go:2774 +0xab
mapserver_1          | net/http.(*conn).serve(0xc0117f30e0, 0xcfbae0, 0xc084e98f00)
mapserver_1          | 	/usr/lib/go-1.12/src/net/http/server.go:1878 +0x84c
mapserver_1          | created by net/http.(*Server).Serve
mapserver_1          | 	/usr/lib/go-1.12/src/net/http/server.go:2884 +0x2f4

```

**Comment by thomasrudin** [comment]
```
mapserver_1          | 2019/03/21 16:18:35 http: panic serving 172.30.0.9:53816: runtime error: invalid memory address or nil pointer dereference
mapserver_1          | goroutine 3879816 [running]:
mapserver_1          | net/http.(*conn).serve.func1(0xc04c0fafa0)
mapserver_1          |  /usr/lib/go-1.12/src/net/http/server.go:1769 +0xc9
mapserver_1          | panic(0xb42580, 0x1334f80)
mapserver_1          |  /usr/lib/go-1.12/src/runtime/panic.go:522 +0x1b5
mapserver_1          | github.com/gorilla/websocket.(*Conn).WriteMessage(0x0, 0x1, 0xc03306e000, 0x48, 0xa8, 0x0, 0xcf16a0)
mapserver_1          |  /root/go/pkg/mod/github.com/gorilla/websocket@v1.4.0/conn.go:742 +0x37
mapserver_1          | mapserver/web.(*WS).ServeHTTP(0xc000094400, 0xcfcea0, 0xc0001a42a0, 0xc04e8de000)
mapserver_1          |  /server/web/ws.go:72 +0x1ba
mapserver_1          | net/http.(*ServeMux).ServeHTTP(0xc00055a040, 0xcfcea0, 0xc0001a42a0, 0xc04e8de000)
mapserver_1          |  /usr/lib/go-1.12/src/net/http/server.go:2375 +0x1d6
mapserver_1          | net/http.serverHandler.ServeHTTP(0xc000146000, 0xcfcea0, 0xc0001a42a0, 0xc04e8de000)
mapserver_1          |  /usr/lib/go-1.12/src/net/http/server.go:2774 +0xab
mapserver_1          | net/http.(*conn).serve(0xc04c0fafa0, 0xcfe160, 0xc00417d900)
mapserver_1          |  /usr/lib/go-1.12/src/net/http/server.go:1878 +0x84c
mapserver_1          | created by net/http.(*Server).Serve
mapserver_1          |  /usr/lib/go-1.12/src/net/http/server.go:2884 +0x2f4

```
