### ISSUE TITLE
Placing a smartshop cause mapserver crash

### ISSUE THREAD

**Issue by Rafi594** [thomasrudin-mt/mapserver#8]
Traceback :

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x782af8]

goroutine 13 [running]:
mapserver/mapobjectdb/sqlite.(*Sqlite3Accessor).AddMapData(0xc000469860, 0x0, 0x3, 0xb)
	/app/mapobjectdb/sqlite/mapobjects.go:74 +0x58
mapserver/mapobject.(*Listener).OnEvent.func1(0x1, 0x3, 0xb)
	/app/mapobject/setup.go:70 +0x54a
mapserver/mapblockparser.IterateMapblock(0xc0000d16e0)
	/app/mapblockparser/iterate.go:7 +0x41
mapserver/mapobject.(*Listener).OnEvent(0xc0004699e0, 0xad8850, 0x11, 0xa4bb20, 0xc0004063c0)
	/app/mapobject/setup.go:53 +0x274
mapserver/eventbus.(*Eventbus).Emit(0xc00017ef20, 0xad8850, 0x11, 0xa4bb20, 0xc0004063c0)
	/app/eventbus/eventbus.go:35 +0xcc
mapserver/mapblockaccessor.(*MapBlockAccessor).FindMapBlocksByMtime(0xc00017ef40, 0x5c5ff0c8, 0x3e8, 0xc00014a120, 0x1, 0x1, 0x7593ca, 0xc00014e180, 0xc000054d18)
	/app/mapblockaccessor/mapblockaccessor.go:102 +0x762
mapserver/tilerendererjob.incrementalRender(0xc000149110, 0xc0000a0540)
	/app/tilerendererjob/incremental.go:28 +0x26a
mapserver/tilerendererjob.Job(0xc000149110)
	/app/tilerendererjob/job.go:35 +0x186
created by main.main
	/app/main.go:61 +0x303
```

**Comment by thomasrudin** [comment]
Yeah, that was my mistake: i was a excited and added a lot of mapbjects to capture on the map but only tested a few of them. The shop-integration needs more work anyway. Some kind of search like on the old mapserver (https://pandorabox.io/map/search.html) would be cool...
